/*
 * The words of the playground's page in Tajik (the default), Russian and
 * English. Messages of the compiler and of running programs come from the
 * diagnostics catalog (src/diagnostics), in the language chosen here.
 * New Tajik words are listed in docs/glossary.tj.md.
 */
window.SOMON_STRINGS = {
  tj: {
    title: 'Майдони озмоиш',
    example: 'Намуна',
    chooseExample: '— намунаро интихоб кунед —',
    run: 'Иҷро',
    stop: 'Қатъ',
    share: 'Пайванд',
    showJs: 'Нишон додани JavaScript',
    learningMode: 'Реҷаи таълимӣ',
    language: 'Забон',
    timeLimit: 'Вақти иҷро',
    seconds: '{n} сония',
    code: 'Барнома',
    codeLabel: 'Коди барнома',
    input: 'Вуруд',
    inputHint: 'Ҳар сатр — як вуруд барои хондан() ё хонданиРақам()',
    output: 'Натиҷа',
    javascript: 'JavaScript',
    running: 'Иҷро мешавад…',
    done: 'Иҷро шуд ({ms} мс).',
    failed: 'Барнома бо хато қатъ шуд.',
    notCompiled: 'Барнома компайл нашуд.',
    nothingPrinted: 'Барнома ҳеҷ чиз чоп накард.',
    timeout: 'Барнома аз ҳад зиёд дароз кор кард — шояд давраи беохир?',
    stopped: 'Барнома қатъ карда шуд.',
    outputLimit: 'Натиҷа хеле дароз аст: танҳо {n} сатри аввал нишон дода шуд.',
    linkCopied: 'Пайванд нусха шуд: онро ба дигарон фиристед.',
    linkReady: 'Пайванд дар сатри суроға аст: онро нусха кунед.',
    noWorker: 'Ин браузер барномаро иҷро карда наметавонад. Браузери навтарро кушоед.',
    line: 'Сатри {n}',
    download: 'Захира барои кор бе интернет',
  },
  ru: {
    title: 'Песочница',
    example: 'Пример',
    chooseExample: '— выберите пример —',
    run: 'Запустить',
    stop: 'Остановить',
    share: 'Ссылка',
    showJs: 'Показать JavaScript',
    learningMode: 'Режим обучения',
    language: 'Язык',
    timeLimit: 'Время выполнения',
    seconds: '{n} с',
    code: 'Программа',
    codeLabel: 'Код программы',
    input: 'Ввод',
    inputHint: 'Каждая строка — один ввод для хондан() или хонданиРақам()',
    output: 'Вывод',
    javascript: 'JavaScript',
    running: 'Выполняется…',
    done: 'Выполнено ({ms} мс).',
    failed: 'Программа остановилась с ошибкой.',
    notCompiled: 'Программа не скомпилирована.',
    nothingPrinted: 'Программа ничего не вывела.',
    timeout: 'Программа работала слишком долго — может быть, бесконечный цикл?',
    stopped: 'Программа остановлена.',
    outputLimit: 'Вывод слишком длинный: показаны только первые {n} строк.',
    linkCopied: 'Ссылка скопирована: отправьте её другим.',
    linkReady: 'Ссылка в адресной строке: скопируйте её.',
    noWorker: 'Этот браузер не может выполнить программу. Откройте более новый браузер.',
    line: 'Строка {n}',
    download: 'Сохранить для работы без интернета',
  },
  en: {
    title: 'Playground',
    example: 'Example',
    chooseExample: '— choose an example —',
    run: 'Run',
    stop: 'Stop',
    share: 'Link',
    showJs: 'Show JavaScript',
    learningMode: 'Learning mode',
    language: 'Language',
    timeLimit: 'Time limit',
    seconds: '{n} s',
    code: 'Program',
    codeLabel: 'Program code',
    input: 'Input',
    inputHint: 'Each line is one input for хондан() or хонданиРақам()',
    output: 'Output',
    javascript: 'JavaScript',
    running: 'Running…',
    done: 'Done ({ms} ms).',
    failed: 'The program stopped with an error.',
    notCompiled: 'The program did not compile.',
    nothingPrinted: 'The program printed nothing.',
    timeout: 'The program ran for too long — an endless loop, perhaps?',
    stopped: 'The program was stopped.',
    outputLimit: 'The output is too long: only the first {n} lines are shown.',
    linkCopied: 'The link was copied: send it to others.',
    linkReady: 'The link is in the address bar: copy it.',
    noWorker: 'This browser cannot run the program. Open a newer browser.',
    line: 'Line {n}',
    download: 'Save for offline use',
  },
};
