import type { DiagnosticParams } from '../../src/diagnostics/types';

/**
 * Values for every message and hint of the diagnostics catalog, in every
 * shape a template distinguishes: tests/diagnostics-catalog.test.ts renders
 * each, scripts/glossary-messages.js lists the first in docs/glossary.tj.md.
 */
/** Values for each message, in every shape a template distinguishes. */
export const SAMPLES: Readonly<Record<string, DiagnosticParams[]>> = {
  PARSE_MISSING_CLOSE: [
    { close: '}', open: '{', line: 4, openLine: 2 },
    { close: ')', open: '(', line: 1, openLine: 1 },
    { close: ']', open: '[', line: 3 },
  ],
  PARSE_UNMATCHED_CLOSE: [{ close: '}' }],
  PARSE_EXPECTED_OPEN: [{ open: '{' }, { open: '{', after: 'кӯшиш' }],
  PARSE_CONDITION_PARENS: [{ keyword: 'агар', example: 'агар (х > 0) { … }' }],
  PARSE_EXPECTED_SEMICOLON: [{ found: '{' }, {}],
  PARSE_EXPECTED_TOKEN: [{ expected: ':', found: ';' }, { expected: ['гирифтан', 'ниҳоят'] }],
  PARSE_EXPECTED_NAME: [
    { what: 'variable', found: '5' },
    { what: 'module' },
    { what: 'unknown kind', found: ';' },
  ],
  PARSE_EXPECTED_EXPRESSION: [{ found: ';' }, {}],
  PARSE_UNEXPECTED_TOKEN: [{ found: 'вагарна' }, {}],
  PARSE_DUPLICATE_DEFAULT_CASE: [{}],
  PARSE_SHORTHAND_INITIALIZER: [{}],
  PARSE_INVALID_MODIFIER: [{ modifier: 'статикӣ', detail: "'статикӣ' modifier already seen" }],
  PARSE_INVALID_DECLARATION: [{ detail: 'Initializers are not allowed in ambient contexts' }],
  PARSE_INVALID_TYPE: [{ detail: 'Tuple members must all have names or all not have names' }],
  PARSE_INVALID_IMPORT_EXPORT: [{ detail: 'A type-only import can specify a default import' }],
  PARSE_INVALID_CLASS_MEMBER: [{ detail: 'Getter must not have any formal parameters' }],
  PARSE_TOO_DEEP: [{}],
  PARSE_INVALID_SYNTAX: [{ detail: 'Invalid optional chain from new expression' }],
  LEX_UNTERMINATED_STRING: [{ quote: '"' }],
  LEX_UNTERMINATED_TEMPLATE: [{}],
  LEX_UNTERMINATED_COMMENT: [{}],
  LEX_INVALID_NUMBER: [{ reason: 'leading zero is not allowed' }],
  LEX_INVALID_ESCAPE: [{}],
  LEX_UNEXPECTED_CHARACTER: [{ character: '@' }],
  LEX_INVALID_REGEXP: [{ detail: 'Invalid regular expression: /(/: Unterminated group' }],
  TYPE_NOT_ASSIGNABLE: [
    { source: '"панҷ"', target: 'рақам' },
    { source: 'сатр', target: 'рақам' },
    { source: 'true', target: 'сатр' },
  ],
  'TYPE_NOT_ASSIGNABLE.return': [{ source: '"а"', target: 'рақам' }],
  'TYPE_NOT_ASSIGNABLE.property': [
    { source: '5', target: 'сатр', property: 'ном' },
    { source: 'рақам', target: 'сатр', property: 'ном' },
  ],
  'TYPE_NOT_ASSIGNABLE.excessProperty': [{ property: 'синну', target: 'Корбар' }],
  'TYPE_NOT_ASSIGNABLE.conversion': [{ source: 'рақам', target: 'сатр' }],
  'TYPE_NOT_ASSIGNABLE.constAssertion': [{}],
  'TYPE_NOT_ASSIGNABLE.satisfies': [{ source: 'рақам', expected: 'сатр' }],
  UNDEFINED_IDENTIFIER: [{ name: 'нм' }],
  'UNDEFINED_IDENTIFIER.parameter': [{ name: 'х' }],
  PROPERTY_NOT_FOUND: [
    { name: 'дарози', type: 'рақам[]' },
    { name: 'дарозӣ', jsName: 'length', type: 'рақам' },
    { name: 'дорад', jsName: 'includes', type: 'Set<рақам>', mapSet: 'yes' },
  ],
  'PROPERTY_NOT_FOUND.static': [{ name: 'нест', class: 'Синф' }],
  'PROPERTY_NOT_FOUND.builtinObject': [
    { name: 'сабтт', object: 'чоп' },
    { name: 'дарозӣ', jsName: 'length', object: 'Риёзӣ' },
  ],
  'PROPERTY_NOT_FOUND.noDefaultExport': [{ module: './м' }],
  'PROPERTY_NOT_FOUND.noExportedMember': [{ module: './м', name: 'х' }],
  ARGUMENT_COUNT_MISMATCH: [
    { function: 'ҷамъ', min: 2, max: 2, got: 1 },
    { function: 'ф', min: 1, max: 2, got: 3 },
    { min: 1, got: 0 },
  ],
  ARGUMENT_TYPE_MISMATCH: [
    { index: 1, function: 'ф', expected: 'рақам', got: '"а"' },
    { index: 2, expected: 'сатр', got: 'true' },
  ],
  POSSIBLY_NULL: [{ reference: 'х', values: ['холӣ'] }, { values: ['холӣ', 'беқимат'] }],
  READONLY_ASSIGNMENT: [{ name: 'ном' }],
  'READONLY_ASSIGNMENT.element': [
    { reference: 'р', type: 'танҳохонӣ рақам[]' },
    { type: 'танҳохонӣ рақам[]' },
  ],
  USED_BEFORE_INITIALIZATION: [{ name: 'ном' }],
  NO_MATCHING_OVERLOAD: [
    { function: 'ф', overloads: '(х: рақам) => сатр' },
    { overloads: '(х: true) => рақам' },
  ],
  'INVALID_OVERRIDE.noBase': [{ class: 'А' }],
  'INVALID_OVERRIDE.notInBase': [{ base: 'Асос' }],
  TYPE_ONLY_IMPORT_VALUE: [{ name: 'Т' }],
  ABSTRACT_INSTANTIATION: [{ class: 'Шакл' }],
  'CONSTANT_CONDITION.truthy': [{}],
  'CONSTANT_CONDITION.falsy': [{}],
  'CONSTANT_CONDITION.neverNullish': [{}],
  'CONSTANT_CONDITION.alwaysNullish': [{}],
  CLASS_NOT_FOUND: [{ name: 'Нест' }],
  INVALID_EXTENDS: [
    { class: 'А', parent: 'И', kind: 'interface' },
    { class: 'А', parent: 'ф', kind: 'function' },
  ],
  CIRCULAR_INHERITANCE: [{ class: 'А' }],
  'CIRCULAR_INHERITANCE.self': [{ class: 'А' }],
  NOT_CALLABLE: [{ name: 'математика' }],
  CONST_ASSIGNMENT: [{ name: 'х' }],
  ASSIGNMENT_IN_CONDITION: [{}],
  CODEGEN_REDECLARED: [{ name: 'х' }],
  CODEGEN_RESERVED_WORD: [{ name: 'class' }],
  'CODEGEN_OUTSIDE_LOOP.break': [{}],
  'CODEGEN_OUTSIDE_LOOP.continue': [{}],
  CODEGEN_AWAIT_OUTSIDE_ASYNC: [{}],
  CODEGEN_INVALID_LABEL: [{ name: 'берун', detail: "Undefined label 'берун'" }],
  CODEGEN_INVALID: [{ detail: 'Private fields can not be deleted' }],
  TARGET_UNSUPPORTED: [
    { detail: 'BigInt literals are not available when targeting lower than ES2020' },
  ],
  OPTION_INVALID: [{ detail: "Unknown target 'es1'" }],
  MODULE_NOT_FOUND: [{ specifier: './нест' }],
  MODULE_FILE_NOT_FOUND: [{ file: 'барнома.som' }],
  CIRCULAR_DEPENDENCY: [{ cycle: 'а.som → б.som → а.som' }],
  MODULE_ERROR: [{ detail: 'Invalid JSON in маълумот.json' }],
  RUNTIME_READ_OF_NOTHING: [{ property: 'дарозӣ', value: 'беқимат' }],
  RUNTIME_WRITE_TO_NOTHING: [{ property: 'ном', value: 'холӣ' }],
  RUNTIME_NOT_DEFINED: [{ name: 'window' }],
  RUNTIME_BEFORE_DECLARATION: [{ name: 'х' }],
  RUNTIME_NOT_A_FUNCTION: [{ name: 'о.ф' }],
  RUNTIME_NOT_A_CONSTRUCTOR: [{ name: 'к' }],
  RUNTIME_NOT_ITERABLE: [{ name: 'х' }],
  RUNTIME_STACK_OVERFLOW: [{}],
  RUNTIME_INVALID_ARRAY_LENGTH: [{}],
  RUNTIME_CONST_ASSIGNMENT: [{}],
  RUNTIME_THROWN: [{ message: 'Ба сифр тақсим кардан мумкин нест' }],
  RUNTIME_ERROR: [{ name: 'SyntaxError', message: 'Unexpected end of JSON input' }],
};

export const HINT_SAMPLES: Readonly<Record<string, DiagnosticParams>> = {
  DID_YOU_MEAN: { name: 'агар' },
  ENGLISH_KEYWORD: { english: 'if', tajik: 'агар' },
  DECLARE_FIRST: {},
  ARGUMENT_COMMA: {},
  FOR_SEMICOLONS: {},
  USE_TAG: {},
  NO_REDECLARE: { name: 'х' },
  NUMBER_IN_QUOTES: { value: '5' },
  HAS_FOR_MAP_SET: {},
  RENAME: {},
  CHECK_PATH: {},
  INDEX_OUT_OF_RANGE: {},
  CHECK_VALUE: { value: 'беқимат' },
  STOP_CONDITION: {},
  DECLARE_BEFORE_USE: {},
  SHOW_STACK: {},
};
